[listen]
host = "0.0.0.0"
port = 8989

[log]
file = { enabled = true, level = "info", dir = "logs", name_prefix = "app.log" }
console = { enabled = true, level = "trace" }                                    # 可选:  trace, debug, info, warn, error

[namesilo]
url = "https://www.namesilo.com/api" # Namesilo API 地址
key = ""                             # API Key（从环境变量传入）
domain = "1554486.xyz"               # 域名
rrhost = "t"                         # 要使用的主机名（无需包含“.DOMAIN”）
rrttl = 7207                         # 此记录的 TTL（如未提供，默认为 7207）
